# This is a basic workflow to help you get started with Actions

name: move issues to project

# Controls when the workflow will run
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2.0.0
        with:
          project-name: 'bug and feature request tracking'
          column-name: 'New'
        
