# This is a basic workflow to help you get started with Actions

name: move issues to project

# Controls when the workflow will run
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.3.0

        with:
          project-url: 'https://github.com/users/DrVinnEck/projects/1'
          github-token: ${{ secrets.DVE_GITHUB_TOKEN }}
        
